### ISSUE TITLE
npm start script assumes nodemon is installed

### ISSUE THREAD

**Issue by sbwheeler** [queerviolet/bones#12]
Ran into this issue when deploying a bones app to heroku. The npm start script uses nodemon, but nodemon is not listed in any of the npm dependencies, so bones is essentially assuming that nodemon is installed globally. If you don't install it locally, your npm start script will hit errors when deployed to heroku.

**Comment by glebec** [comment]
Yes, it would seem it should be added as a `devDependency`. EDIT: `nodemon` probably shouldn't be used in Heroku at all — doesn't it use its own process manager to enable restarts?

**Comment by glebec** [comment]
Turns out this was added to the dependencies list in https://github.com/queerviolet/bones/commit/5359b1343b0071a314b0761428f62f6d1e63f92f. This issue can therefore be closed. However I want to follow up on the issue of using `nodemon` in a Heroku app, so I will make that a separate issue.
