### ISSUE TITLE
Prevent spurious PRs

### ISSUE THREAD

**Issue by glebec** [queerviolet/bones#16]
When people use Bones to start their own projects, they often mistakenly open project-based PRs against it. This pollutes the PR history with tons of irrelevant side information, making it hard to see the development cycle of Bones proper.

One potential strategy for heading this off at the pass would be to discourage forking of Bones for starting apps. Forking would only for Bones development or spinoffs. This would basically just be a README update.

I don't see an obvious way to enforce this distinction programmatically. FSG didn't have this issue because it was an npm package, but that made it impossible to merge upstream changes into in-progress apps — a feature which we often wished for, and which Bones does have, being a straight up repo.

**Comment by omriAckley** [comment]
They could do a "manual" fork (maybe this is what you are saying too, I'm not sure). So they'd just clone bones, then create *another* github repo, then add that other repo as another remote. If so we should probably tell them to have bones be "upstream" and their project github repo be "origin".

**Comment by glebec** [comment]
That's the exact approach already in the README _except_ that the README also says you can do a straight up fork instead if you prefer. My proposal is basically to change that to say _don't_ fork (unless your intent is to develop Bones or a spinoff itself).

**Comment by omriAckley** [comment]
Haha I didn't even realize!

Yes, I completely agree.

**Comment by glebec** [comment]
Closed in https://github.com/FullstackAcademy/bones/commit/eb16ece8281cea6725cfd7e80c96a45f67310ac7.
