### ISSUE TITLE
Upgrade to Webpack 2?

### ISSUE THREAD

**Issue by glebec** [queerviolet/bones#20]
https://medium.com/webpack/webpack-2-and-beyond-40520af9067f#.s1sqjeiu0

**Comment by omriAckley** [comment]
Doesn't seem urgent, but I suppose we might as well? I mean we will at some point right...

**Comment by glebec** [comment]
Closed for Fullstack in https://github.com/FullstackAcademy/bones/commit/211b27e4fe0fee66be6c3a5dae0049042a3f384b. Can keep this issue open if @queerviolet wants to follow suit in this repo, else close it.
