### ISSUE TITLE
Perhaps re-init Fullstack Bones as a standalone repo?

### ISSUE THREAD

**Issue by glebec** [queerviolet/bones#24]
Many of the issues on queerviolet/Bones are Fullstack-centric. This is because issues cannot be opened against forks (which Fullstack's Bones currently is). We could:

* Re-init the Fullstack copy as a standalone repo (edit: with shared commit history)
* Transfer ownership of the existing repo to Fullstack (which I guess would make this repo a fork? I've never tried this)
* Leave things as they are

Thoughts?

**Comment by omriAckley** [comment]
I vote for bullet number 2, transferring ownership. Seems like the "root" skeleton should be under Fullstack.

**Comment by glebec** [comment]
@queerviolet — any thoughts?

**Comment by queerviolet** [comment]
Huh. I didn't realize there was any "root" repo--that's a concept foreign to git. Can we just open issues against the Fullstack fork?

If that doesn't work, there's no reason to "transfer ownership", per se. We could just clone bones and push a new repo.

**Comment by glebec** [comment]
> Can we just open issues against the Fullstack fork?

Annoyingly, that doesn't seem to be possible. Blah.

> We could just clone bones and push a new repo.

Yeah, that's my first suggestion in the top comment — I have no opinion between ownership vs standalone repo. I've used a standalone clone at least once before and it worked fine, just requires an extra step to manually transfer any existing issues. EDIT: though actually I don't know that "transferring ownership" also moves over the issues — I just assume so but haven't tested it.

**Comment by glebec** [comment]
[Good news everyone!](https://www.youtube.com/watch?v=qjRDXBAu3cY) It turns out forks CAN have issues — but you have to turn them on manually. I just did so for Fullstack and I'm going to port many / most of the issues on https://github.com/queerviolet/bones over to https://github.com/fullstackacademy/bones.

**Comment by glebec** [comment]
This issue was moved to FullstackAcademy/bones#73
